
public class Calculator extends javax.swing.JFrame {
        int num1,num2;
        int total;
        String operators;
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        answer = new javax.swing.JTextField();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        cdiv = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        cmul = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        c8 = new javax.swing.JButton();
        c9 = new javax.swing.JButton();
        csub = new javax.swing.JButton();
        cequal = new javax.swing.JButton();
        c0 = new javax.swing.JButton();
        cdot = new javax.swing.JButton();
        cadd = new javax.swing.JButton();
        clr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setLayout(null);

        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });
        jPanel1.add(answer);
        answer.setBounds(62, 39, 401, 41);

        c1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        c1.setText("1");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1);
        c1.setBounds(46, 115, 73, 44);

        c2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        c2.setText("2");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel1.add(c2);
        c2.setBounds(164, 115, 74, 44);

        c3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        c3.setText("3");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        jPanel1.add(c3);
        c3.setBounds(295, 115, 72, 44);

        cdiv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cdiv.setText("\\");
            cdiv.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cdivActionPerformed(evt);
                }
            });
            jPanel1.add(cdiv);
            cdiv.setBounds(409, 116, 60, 44);

            c4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            c4.setText("4");
            c4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    c4ActionPerformed(evt);
                }
            });
            jPanel1.add(c4);
            c4.setBounds(46, 199, 73, 41);

            c5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            c5.setText("5");
            c5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    c5ActionPerformed(evt);
                }
            });
            jPanel1.add(c5);
            c5.setBounds(170, 200, 70, 41);

            c6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            c6.setText("6");
            c6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    c6ActionPerformed(evt);
                }
            });
            jPanel1.add(c6);
            c6.setBounds(300, 200, 70, 42);

            cmul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            cmul.setText("*");
            cmul.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cmulActionPerformed(evt);
                }
            });
            jPanel1.add(cmul);
            cmul.setBounds(409, 200, 60, 42);

            c7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            c7.setText("7");
            c7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    c7ActionPerformed(evt);
                }
            });
            jPanel1.add(c7);
            c7.setBounds(46, 284, 73, 41);

            c8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            c8.setText("8");
            c8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    c8ActionPerformed(evt);
                }
            });
            jPanel1.add(c8);
            c8.setBounds(170, 280, 70, 41);

            c9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            c9.setText("9");
            c9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    c9ActionPerformed(evt);
                }
            });
            jPanel1.add(c9);
            c9.setBounds(300, 280, 70, 41);

            csub.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            csub.setText("-");
            csub.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    csubActionPerformed(evt);
                }
            });
            jPanel1.add(csub);
            csub.setBounds(409, 284, 60, 41);

            cequal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            cequal.setText("=");
            cequal.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cequalActionPerformed(evt);
                }
            });
            jPanel1.add(cequal);
            cequal.setBounds(46, 364, 73, 41);

            c0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            c0.setText("0");
            c0.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    c0ActionPerformed(evt);
                }
            });
            jPanel1.add(c0);
            c0.setBounds(170, 360, 70, 41);

            cdot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            cdot.setText(".");
            cdot.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cdotActionPerformed(evt);
                }
            });
            jPanel1.add(cdot);
            cdot.setBounds(300, 360, 70, 41);

            cadd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            cadd.setText("+");
            cadd.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    caddActionPerformed(evt);
                }
            });
            jPanel1.add(cadd);
            cadd.setBounds(409, 364, 60, 41);

            clr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            clr.setText("CLR");
            clr.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    clrActionPerformed(evt);
                }
            });
            jPanel1.add(clr);
            clr.setBounds(350, 440, 55, 30);

            getContentPane().add(jPanel1);
            jPanel1.setBounds(0, 0, 530, 500);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
      answer.setText(answer.getText()+"2");
    }//GEN-LAST:event_c2ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
       answer.setText(answer.getText()+"4");
    }//GEN-LAST:event_c4ActionPerformed

    private void cmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmulActionPerformed
        num1=Integer.parseInt(answer.getText());
          answer.setText("");
          operators="*";
    }//GEN-LAST:event_cmulActionPerformed

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
            answer.setText(answer.getText()+"1");  
    }//GEN-LAST:event_c1ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
       answer.setText(answer.getText()+"3");   
    }//GEN-LAST:event_c3ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        answer.setText(answer.getText()+"5");  
    }//GEN-LAST:event_c5ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        answer.setText(answer.getText()+"6");  
    }//GEN-LAST:event_c6ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
        answer.setText(answer.getText()+"7");  
    }//GEN-LAST:event_c7ActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
        answer.setText(answer.getText()+"8");  
    }//GEN-LAST:event_c8ActionPerformed

    private void c9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c9ActionPerformed
        answer.setText(answer.getText()+"9");  
    }//GEN-LAST:event_c9ActionPerformed

    private void c0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c0ActionPerformed
        answer.setText(answer.getText()+"0");  
    }//GEN-LAST:event_c0ActionPerformed

    private void cdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdivActionPerformed
        num1=Integer.parseInt(answer.getText());
          answer.setText("");
          operators="/";
    }//GEN-LAST:event_cdivActionPerformed

    private void csubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csubActionPerformed
        num1=Integer.parseInt(answer.getText());
          answer.setText("");
          operators="-";
    }//GEN-LAST:event_csubActionPerformed

    private void caddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caddActionPerformed
        num1=Integer.parseInt(answer.getText());
          answer.setText("");
          operators="+";
    }//GEN-LAST:event_caddActionPerformed

    private void cdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdotActionPerformed
        num1=Integer.parseInt(answer.getText());
          answer.setText("");
          operators=".";
    }//GEN-LAST:event_cdotActionPerformed

    private void cequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cequalActionPerformed
        num2=Integer.parseInt(answer.getText());
        int ans = 0;
        if(operators.equals("+"))
        {
            ans = num1+num2;
        }
        if(operators.equals("-"))
        {
            ans = num1-num2;
        }
        if(operators.equals( "*"))
        {
            ans = num1*num2;
        }
        if(operators.equals("/"))
        {
            ans = num1/num2;
        }
        answer.setText(""+ans);
        operators=null;
    }//GEN-LAST:event_cequalActionPerformed

    private void clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrActionPerformed
        answer.setText("");
    }//GEN-LAST:event_clrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JButton c0;
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JButton c7;
    private javax.swing.JButton c8;
    private javax.swing.JButton c9;
    private javax.swing.JButton cadd;
    private javax.swing.JButton cdiv;
    private javax.swing.JButton cdot;
    private javax.swing.JButton cequal;
    private javax.swing.JButton clr;
    private javax.swing.JButton cmul;
    private javax.swing.JButton csub;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
